<?php
// build section needs to be revisited. the build.php file is generated by a bash script on brandastic.com, but
// we are not using a bashscript for deployment, need to refactor how brandastic.com generates the build file if we
// dont want to use a bash script, or incorporate the bash script into our workflow.
$buildVersionPath = __DIR__ . '/build.php';
if(is_readable($buildVersionPath)) {
    include($buildVersionPath);
} else {
   define('BRANDPRESS_BUILD', time());
}

// allow site admin email to be changed without confirmation
remove_action('add_option_new_admin_email', 'update_option_new_admin_email');
remove_action('update_option_new_admin_email', 'update_option_new_admin_email');

/**
 * Disable the confirmation notices when an administrator
 * changes their email address.
 *
 * @see http://codex.wordpress.com/Function_Reference/update_option_new_admin_email
 */
function custom_update_option_new_admin_email($old_value, $value)
{
    update_option('admin_email', $value);
}

add_action('add_option_new_admin_email', 'custom_update_option_new_admin_email', 10, 2);
add_action('update_option_new_admin_email', 'custom_update_option_new_admin_email', 10, 2);

// Include all files in the includes directory
foreach (glob(get_stylesheet_directory() . '/includes/*.php') as $filename)
{
    /** @noinspection PhpIncludeInspection */
    require($filename);
}